const actionTypes = {
    SET_MOVIES: 'SET_MOVIES',
    SET_SELECTED_YEAR: 'SET_SELECTED_YEAR',
    SET_SELECTED_GENRES: 'SET_SELECTED_GENRES',
    SET_GENRES: 'SET_GENRES',
    SET_LIST_VIEW: 'SET_LIST_VIEW',
    SET_MOVIE: 'SET_MOVIE',
    SET_IMAGES: 'SET_IMAGES',
    SET_SELECTED_DAY : 'SET_SELECTED_DAY', 
}
export default actionTypes;